version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: babylist_mongo
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_USERNAME: babylistUser
      MONGO_INITDB_PASSWORD: pass4babyList
      MONGO_INITDB_DATABASE: babylist
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  mongo-express:
    image: mongo-express
    container_name: babylist_mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      #ME_CONFIG_MONGODB_PORT: 27017
      #ME_CONFIG_MONGODB_SERVER: mongo


